### ISSUE TITLE
Request features

### ISSUE THREAD

**Issue by khoaakt** [KTTECHTeam/KT-Browser-DEPRECATED#1]
- [x] Reader Mode
- [x] Search engines manager
- [x] Right-click menu on tab
- [x] Block advertises
- [x] Block unsafe web
- [x] Private Mode
- [x] Contextmenu
- [ ] Support NPAPI
- [ ] Redesign UI/UX
- [ ] Language
- [ ] Low-spec mode
- [ ] Sync between other browsers
- [ ] Improved performance
- [ ] First start
- [ ] Search box
- [ ] Use webpack

**Comment by Sential** [comment]
I would suggest to rewrite this, because [`WebExpress2`](https://github.com/Sential/WebExpress2) is the last version, has slow performance, and was written in jQuery (which is quite old technology). Have a look at my new browser written in React - [`Wexond`](https://github.com/wexond/wexond).

**Comment by khoaakt** [comment]
@Sential Thanks for your necessary information. However, it will take me a long time to get back to this project because of my life. Then I'd rewrite it from scratch. 👍 
P/S: just merged your pull, thanks.

**Comment by khoaakt** [comment]
Close, this project will be continued in a different repo in the future because license issues.
